# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       automoc

# >> macros
# << macros

Summary:    Automatic moc for Qt 4 packages
Version:    0.9.88
Release:    1
Group:      Development/Tools
License:    BSD
URL:        http://websvn.kde.org/trunk/kdesupport/automoc/
Source0:    %{name}-%{version}.tar.bz2
Source100:  automoc.yaml
Requires:   libqt-devel
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  cmake
BuildRequires:  gcc-c++
Provides:   automoc4 = %{version}

%description
This package contains the automoc4 binary which is used to run moc on the right
binaries in a Qt 4 or KDE 4 application.

Moc is the meta object compiler which is a much used tool when using the Qt
toolkit.


%prep
%setup -q -n %{name}-%{version}/%{name}

# >> setup
# << setup

%build
# >> build pre
mkdir %{_target_platform}
cd %{_target_platform} && cmake .. -DCMAKE_INSTALL_PREFIX="%{_prefix}" -DCMAKE_C_COMPILER:FILEPATH="cc" -DCMAKE_CXX_COMPILER:FILEPATH="g++" -DCMAKE_C_FLAGS="%{optflags}" -DCMAKE_CXX_FLAGS="%{optflags}" -DCMAKE_SKIP_RPATH=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_SKIP_RPATH:BOOL=OFF -DCMAKE_USE_RELATIVE_PATHS=ON -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined" -DCMAKE_MODULE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined" -DCMAKE_EXE_LINKER_FLAGS="-Wl,--as-needed -Wl,--no-undefined"
make %{?jobs:-j%jobs}
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
make -C %{_target_platform} install DESTDIR=%{buildroot}
# << install post

%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/automoc4
%{_libdir}/automoc4/Automoc4Config.cmake
%{_libdir}/automoc4/Automoc4Version.cmake
%{_libdir}/automoc4/automoc4.files.in
# << files
